### ISSUE TITLE
replace hard coded slashes with os.path.join

### ISSUE THREAD

**Issue by GarryMorrison** [GarryMorrison/Semantic-DB#10]
this will make it more cross platform.

**Comment by GarryMorrison** [comment]
wow! This hits sdb.py, and create-usage-html.py in a whole bunch of places!
Ditto the re-organisation of the code tree heirarchy.

**Comment by gavinfernandes2012** [comment]
I think python automagically handles all this iirc. So we might not need to do this. Within python we'll only have to use the forward slash if this is true.

**Comment by GarryMorrison** [comment]
ahh... that would be good news then.

**Comment by gavinfernandes2012** [comment]
I can confirm that python handles both forward and backward slashes on windows. ((Source)[https://stackoverflow.com/questions/12288679/python-storing-path-names-with-forward-vs-backward-slash])
So we can probably close this issue.
